### PR TITLE
Add CI pipeline

### PR DESCRIPTION
**Pull request by ddugovic**
With each commit, GitHub can automate linting, testing, etc. to verify code quality & performance:
https://github.com/features/actions

### CODE REVIEW

**Comment by PetterS** [comment]
Thanks!!

Github workflows were quite broken last I tried them – they would not run for PRs from forked repositories. 

Maybe e.g. CircleCI instead? But we can do this as well if you prefer.

**Comment by ddugovic** [comment]
As a chess player, I'm glad to help!

Oh, interesting... strange, I think currently https://github.com/ddugovic/realtimechess/actions functions (indicating test failures), although I should learn more about this CircleCI in case maybe it's easier to use.

**Comment by PetterS** [comment]
I don't want to discourage your contributing to this repo! :-) We definitely need CI in the repo if we should have collaboration so I welcome the initiative. 👍 

But I think it would be good to have the tests and checks run on every PR. That was not possible with GH actions and forked repos when we last evaluated them.

**Comment by ddugovic** [comment]
Ah, now I understand the disconnect... currently from a public GH repository's "Actions" view the only ways to observe PR results would be to copy/sync the branch (in this case `github-actions`) from the fork into the upstream repository; or to observe them in the fork's "Actions" view (assuming that developer enabled CI).  So yes, likely CircleCI has an advantage there.

**Comment by ddugovic** [comment]
It turns out that allowing arbitrary code to be run with each PR would allow anyone to mine bitcoins by way of GitHub Actions, so let's just stick with CircleCI.

**Pull request closed without merging**
