### PR TITLE
Create LICENSE

### LINKED ISSUE #1: License?
Is this repository available under an open source license?

### PR DESCRIPTION
**Pull request by janheinrichmerker**
Fixes #1

### CODE REVIEW

**Comment by janheinrichmerker** [comment]
@PetterS Could you please review the added MIT License? I'd love to include this poject in a bundle of open source games I'm creating in university.

**Comment by PetterS** [comment]
Can you change it to a GPL license? I will merge this then.

**Comment by janheinrichmerker** [comment]
To not have the MIT License in Git history, I've created another PR with GPL 3.0: #3

**Comment by PetterS** [comment]
Don't worry, I would have squashed the commits anyway.

**Pull request closed without merging**
